sudo: required
language: generic

services:
- docker

env:
  DOCKER_COMPOSE_VERSION: 1.8

script:
  - docker-compose run style
  - docker-compose run unit-test
  - docker-compose run integration-test_docker
  - docker-compose run integration-test_collectd