version: '2'
services:
  base:
    build: .
    image: collectd-docker-stats:base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/opt/collectd-docker-stats
  collectd:
    extends:
      service: base
    command: collectd -f -T -C /opt/collectd-docker-stats/collectd.conf
  test:
    extends:
      service: base
    command: python -m unittest discover -p '*Test.py' tests
  style:
    extends:
      service: base
    command: flake8 .